name: Generate remaining diffs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-diffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run generate-all-missing-diffs script
        run: pnpm run generate-all-missing-diffs

      - name: Pull latest commits
        run: git pull

      - name: Commit assets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate remaining diffs
          file_pattern: diffs/*

      - name: Commit assets if cancelled
        if: ${{ cancelled() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate remaining diffs
          file_pattern: diffs/*
